service: jfga-stack-web

provider:
  name: aws
  runtime: provided
  stage: ${opt:stage,'dev'}
  region: ap-northeast-1

package:
  exclude:
    - ./**

custom:
  client:
    bucketName: ${cf:jfga-stack-web-${self:provider.stage}.StaticAssetsBucket, ''}
    manageResources: false
    distributionFolder: dist
  buildClient:
    packager: npm
    environment:
      VUE_APP_API_URL: ${cf.ap-northeast-1:jfga-stack-${self:provider.stage}.JFGAApiURL}
      VUE_APP_WEB_URL: ${cf.ap-northeast-1:jfga-stack-${self:provider.stage}.JFGAWebURL}
      VUE_APP_COGNITO_REGION: ap-northeast-1
      VUE_APP_COGNITO_USERPOOL_ID: ${cf.ap-northeast-1:jfga-stack-${self:provider.stage}.JFGAUserPoolId}
      VUE_APP_COGNITO_USERPOOL_APP_CLIENT_ID: ${cf.ap-northeast-1:jfga-stack-${self:provider.stage}.JFGAUserPoolClientUserClient}
      VUE_APP_COGNITO_DOMAIN_NAME: ${cf.ap-northeast-1:jfga-stack-${self:provider.stage}.JFGAUserPoolDomain}
      VUE_APP_COGNITO_REDIRECT_SIGN_IN: ${cf.ap-northeast-1:jfga-stack-${self:provider.stage}.JFGAWebURL}/account/callback
      VUE_APP_COGNITO_REDIRECT_SIGN_OUT: ${cf.ap-northeast-1:jfga-stack-${self:provider.stage}.JFGAWebURL}

resources:
  Resources:
    StaticAssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        WebsiteConfiguration:
          IndexDocument: index.html
    StaticAssetsBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref StaticAssetsBucket
        PolicyDocument:
          Statement:
            - Action: s3:GetObject
              Effect: Allow
              Resource: !Join
                - ''
                - - !GetAtt StaticAssetsBucket.Arn
                  - /*
              Principal: '*'
    JFGAWebDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Aliases:
#            - ${cf.ap-northeast-1:jfga-stack-${self:provider.stage}.JFGACloudFrontCustomDomain}
          CacheBehaviors:
            - AllowedMethods:
                - GET
                - HEAD
              CachedMethods:
                - GET
                - HEAD
              Compress: true
              DefaultTTL: 0
              MaxTTL: 0
              MinTTL: 0
              ForwardedValues:
                QueryString: false
              PathPattern: /
              TargetOriginId: jfga-${opt:stage, 'dev'}-s3
              ViewerProtocolPolicy: redirect-to-https
            - AllowedMethods:
                - GET
                - HEAD
              CachedMethods:
                - GET
                - HEAD
              Compress: true
              DefaultTTL: 0
              MaxTTL: 0
              MinTTL: 0
              ForwardedValues:
                QueryString: false
              PathPattern: index.html
              TargetOriginId: jfga-${opt:stage, 'dev'}-s3
              ViewerProtocolPolicy: redirect-to-https
          Comment: JFGA Web distribution
          CustomErrorResponses:
            - ErrorCode: 403
              ErrorCachingMinTTL: 0
              ResponseCode: 200
              ResponsePagePath: /index.html
            - ErrorCode: 404
              ErrorCachingMinTTL: 0
              ResponseCode: 200
              ResponsePagePath: /index.html
          DefaultCacheBehavior:
            Compress: true
            ForwardedValues:
              QueryString: false
            TargetOriginId: jfga-${opt:stage, 'dev'}-s3
            ViewerProtocolPolicy: redirect-to-https
            DefaultTTL: 0
            MaxTTL: 0
            MinTTL: 0
          DefaultRootObject: index.html
          Enabled: true
          HttpVersion: http2
          Origins:
            - Id: jfga-${opt:stage, 'dev'}-s3
              DomainName: !Select
                - 2
                - Fn::Split:
                    - /
                    - !GetAtt StaticAssetsBucket.WebsiteURL
              CustomOriginConfig:
                OriginProtocolPolicy: http-only
          PriceClass: PriceClass_100
#          ViewerCertificate:
#            AcmCertificateArn: ${cf.ap-northeast-1:jfga-stack-${self:provider.stage}.JFGAWebCertificateArn}
#            SslSupportMethod: sni-only
        Tags:
          - Key: Project
            Value: jfga-${opt:stage, 'dev'}
  Outputs:
    StaticAssetsBucket:
      Value: !Ref StaticAssetsBucket

plugins:
  - serverless-finch
  - serverless-build-client
