version: '3.7'

services:

  frontend:
    container_name: ${PROJECT_NAME}_frontend
    image: bangtx/jfga_frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/app/frontend'
      - './frontend/node_modules:/app/frontend/node_modules'
    env_file: .env
    ports:
      - '1100:1100'
    expose:
      - 1100
    command: ["npm", "run", "serve", "--", "--port", "1100"]

  backend:
    container_name: ${PROJECT_NAME}_backend
    image: bangtx/jfga_backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./backend:/app/backend
    ports:
      - '1000:1000'
    depends_on:
      - db
    entrypoint: [ "poetry", "run" ]
    command: [ "uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "1000" ]

  db:
    container_name: ${PROJECT_NAME}_db
    image: postgres:11
    ports:
      - "1300:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local